# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: MIT
- package:
  - name: stablecoin
  - section:
    - name: exe:stablecoin
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: exe:stablecoin-client
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: test:stablecoin-test
    - message:
      - name: Weeds exported
      - module:
        - name: Tree
        - identifier:
          - ingredients
          - main
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: test:stablecoin-nettest test:stablecoin-test
    - message:
      - name: Module reused between components
      - module:
        - Lorentz.Contracts.Test.Common
    # This function is used only in test:stablecoin-test, but not used
    # in test:stablecoin-nettest, so weeder considers it redundant.
    - message:
      - name: Weeds exported
      - module:
        - name: Lorentz.Contracts.Test.Common
        - identifier:
            - defaultPermissionDescriptor
  - section:
    - name: test:stablecoin-nettest
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
