# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: MIT

<<: !include "./hpack/module.yaml"

name:                stablecoin
version:             1.7.0

extra-source-files:
- README.md
- ChangeLog.md
- test/resources/stablecoin.tz
- test/resources/metadata.tz

synopsis:            FA2-based tezos stablecoin smart contract
category:            Blockchain

description:         Please see the README on GitHub at <https://github.com/tqtezos/stablecoin#readme>

verbatim:
  cabal-version: 2.2

library:
  <<: *lib-common

  dependencies:
    - aeson
    - aeson-casing
    - bytestring
    - caps
    - cleveland
    - containers
    - directory
    - file-embed
    - fmt
    - indigo
    - lorentz
    - megaparsec
    - morley
    - morley-client
    - morley-ledgers
    - morley-metadata
    - morley-prelude
    - optparse-applicative
    - process
    - servant-client
    - template-haskell
    - text
    - uncaught-exception

executables:
  stablecoin-client:
    main: Main.hs
    source-dirs: client

    dependencies:
      - morley-prelude
      - stablecoin

tests:
  stablecoin-test:
    <<: *test-common
    source-dirs:
      - test
      - test-common

    dependencies:
      - aeson
      - bytestring
      - cleveland
      - containers
      - fmt
      - hedgehog
      - hspec
      - lorentz
      - morley
      - morley-ledgers
      - morley-ledgers-test
      - morley-metadata
      - morley-metadata-test
      - morley-prelude
      - mtl
      - optparse-applicative
      - stablecoin
      - tasty
      - tasty-hedgehog
      - tasty-hspec
      - tasty-hunit-compat
      - text

  stablecoin-nettest:
    <<: *test-common
    source-dirs:
      - test-common
      - nettest

    dependencies:
      - aeson
      - cleveland
      - containers
      - fmt
      - lorentz
      - morley
      - morley-client
      - morley-ledgers
      - morley-metadata
      - morley-metadata-test
      - morley-prelude
      - optparse-applicative
      - stablecoin
      - text
      - with-utf8
